### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by alexeyza** [omazhary/chiseler-snake#1]
Milestones:
- [x] Getting the snake to run locally and being able to send it `GET/POST` requests
- [x] Getting the snake to respond to a game `\start` request (with correct info: name, color, etc.)
- [x] Getting the snake to respond to a `\move` request (any response is fine for now)
- [ ] Deploying server to heroku and able to respond to `\start` and `\move` requests as before
- [x] Running a game server locally (via Docker) and having the snake show up in the game
- [ ] Tweaking the snake movement (this is the main part - this perhaps will be done as part of a learning algorithm):
    + [x] Avoid hitting walls
    + [x] Avoid hitting itself
    + [x] Eat food
    + [x] Don't starve
    + [ ] Don't eat too much either
    + [x] Don't collide with others
    + [x] Do head collisions only if larger than the other snake
    + [ ] Optimize movement to not "waste" space that may be needed later
    + [ ] Sabotage other snake's empty space
- [ ] Testing snake against other snakes
- [ ] Add taunting and persona for the snake
- [ ] Make sure snake responds quickly enough

* _feel free to add more milestone and check the ones achieved_
